<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <Platforms>x64</Platforms>
        <UseWindowsForms>true</UseWindowsForms>
        <EnableWindowsTargeting>true</EnableWindowsTargeting>
        <CreateCipx>false</CreateCipx>
        <RootNamespace>BetterNetworkStatus</RootNamespace>
        <AssemblyName>BetterNetworkStatus</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ClassIsland.PluginSdk" Version="2.0.0.1" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.1" />
    </ItemGroup>

    <ItemGroup>
        <None Update="manifest.yml">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="README.md">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="icon.png">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>
</Project>
